package com.angular.model;
// Generated Apr 30, 2020 5:58:29 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "singlepagemusic")
public class Album implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Category category;
	private Singer singer;
	private String name;
	private String picture;
	private Date datenotify;
	private Set<Song> songs = new HashSet<Song>(0);

	public Album() {
	}

	public Album(Category category, Singer singer, Date datenotify) {
		this.category = category;
		this.singer = singer;
		this.datenotify = datenotify;
	}

	public Album(Category category, Singer singer, String name, String picture, Date datenotify, Set<Song> songs) {
		this.category = category;
		this.singer = singer;
		this.name = name;
		this.picture = picture;
		this.datenotify = datenotify;
		this.songs = songs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@JsonIgnore 
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}
	@JsonIgnore 
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsinger", nullable = false)
	public Singer getSinger() {
		return this.singer;
	}

	public void setSinger(Singer singer) {
		this.singer = singer;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "picture", length = 500)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datenotify", nullable = false, length = 26)
	public Date getDatenotify() {
		return this.datenotify;
	}

	public void setDatenotify(Date datenotify) {
		this.datenotify = datenotify;
	}
	@JsonIgnore 
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<Song> getSongs() {
		return this.songs;
	}

	public void setSongs(Set<Song> songs) {
		this.songs = songs;
	}

}
