package com.angular.model;
// Generated Apr 30, 2020 5:58:29 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "singlepagemusic")
public class Category implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	  Integer id;
	  String name;
	  String description;
	  Date datenotify;
	  Set<Album> albums = new HashSet<Album>(0);
	  Set<Song> songs = new HashSet<Song>(0);

	public Category() {
	}

	public Category(Date datenotify) {
		this.datenotify = datenotify;
	}

	public Category(String name, String description, Date datenotify, Set<Album> albums, Set<Song> songs) {
		this.name = name;
		this.description = description;
		this.datenotify = datenotify;
		this.albums = albums;
		this.songs = songs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datenotify", nullable = false, length = 26)
	public Date getDatenotify() {
		return this.datenotify;
	}

	public void setDatenotify(Date datenotify) {
		this.datenotify = datenotify;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "category")
	public Set<Album> getAlbums() {
		return this.albums;
	}
	 
	public void setAlbums(Set<Album> albums) {
		this.albums = albums;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "category")
	public Set<Song> getSongs() {
		return this.songs;
	}
	
	public void setSongs(Set<Song> songs) {
		this.songs = songs;
	}

}
