package com.angular.model;
// Generated Apr 30, 2020 5:58:29 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "session", catalog = "singlepagemusic")
public class Session implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String session;
	private Date datecreate;
	private Set<Playlist> playlists = new HashSet<Playlist>(0);

	public Session() {
	}

	public Session(String session, Date datecreate) {
		this.session = session;
		this.datecreate = datecreate;
	}

	public Session(String session, Date datecreate, Set<Playlist> playlists) {
		this.session = session;
		this.datecreate = datecreate;
		this.playlists = playlists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "session", nullable = false, length = 500)
	public String getSession() {
		return this.session;
	}

	public void setSession(String session) {
		this.session = session;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreate", nullable = false, length = 26)
	public Date getDatecreate() {
		return this.datecreate;
	}

	public void setDatecreate(Date datecreate) {
		this.datecreate = datecreate;
	}
	@JsonIgnore 
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "session")
	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}

}
